### ISSUE TITLE
`amethyst new` doesn't create `.gitignore` file

### ISSUE THREAD

**Issue by White-Oak** [amethyst/tools#10]
I guess it should contain at least `target` folder.

**Comment by ebkalderon** [comment]
D'oh! Thanks for reporting this. We need to add the missing `.gitignore` file to the `new_project.zip` archive, so that it can be included with `amethyst new`. I'd rather not add include `target` folder, though, since new Cargo projects don't have one by default anyway.

**Comment by ebkalderon** [comment]
Scratch my previous comment. See [the proposal given in issue #9](https://github.com/ebkalderon/amethyst_tools/issues/9#issuecomment-182656509) for a better potential fix.

**Comment by ebkalderon** [comment]
This has been fixed by pull request #12. Marking as resolved and closing.
