### ISSUE TITLE
Gives unhelpful error message if git is not installed

### ISSUE THREAD

**Issue by RustigeMan** [amethyst/tools#111]
I didn't have git installed yet on my new laptop and amethyst_tools was giving me a rather unhelpful message when making a new project:

    > amethyst new pong
    error: project creation for project "pong" failed
    caused by: No such file or directory (os error 2)

No such error is displayed now that git is installed.

**Comment by CleanCut** [comment]
👋 I'm closing all PRs and Issues since `amethyst_tools` is being end-of-life'd.  Please see [this forum post](https://community.amethyst.rs/t/end-of-life-for-amethyst-tools-the-cli/1656) for a place to respond and/or discuss the situation rather than here on the repo.
