### ISSUE TITLE
Expose Cargo exit status if non-zero

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/tools#13]
Right now, the Amethyst CLI client always returns zero when calling Cargo commands, regardless of whether Cargo itself returned errors. This is why the `tests.sh` file doesn't work as expected, returning "All tests pass!" even when that's obviously not true (see the comments on pull request #12 for an example).

This isn't too problematic since Amethyst and its toolchain are in the 0.X.Y release stage, but nonetheless this must be fixed before 1.0 rolls around.

**Comment by White-Oak** [comment]
btw, I suppose cargo call should return Result, not Option. Right now option return in case of error is very confusing.

**Comment by ebkalderon** [comment]
@White-Oak I chose `Option` because it looked a little less verbose to me. If I were to choose `Result`, I would have to make the return value be something like `Result<(), &'static str>`, which isn't particularly pretty. **Edit**: It appears this [actually may be standard practice](https://doc.rust-lang.org/std/result/index.html#results-must-be-used)(?)

If a successful Cargo execution isn't meant to return anything, it's much easier to use `Some(error)` and `None`. However, it's a subjective issue of aesthetics, really, and if the use of `Option` is too confusing for people, I'll gladly switch it to `Result`.

**Comment by White-Oak** [comment]
Ah, considering the issue.
Problem in #12 was not about not exposing Cargo fail status, but about tests.sh not checking exit status of `amethyst new`.
I've PRed the fix #14.

**Comment by ebkalderon** [comment]
@White-Oak After thinking about it some more, I've come to agree with your stance on using `Result` over `Option`. However, this should probably be a separate pull request from #15, which implements the basic functionality. One thing at a time...

**Edit**: I'd recommend reducing the verbosity of `Result` a bit with a typedef:

``` rust
pub type CargoStatus = Result<(), &'static str>;
```

That makes things like this look much, much cleaner, similar to `Option`. It's less confusing and more Rusty.

``` rust
pub fn call(args: Vec<&str>) -> CargoStatus {
    // ...

    if output.task.success() {
        Ok(())
    } else {
        Err("Running cargo task failed")
    }
}
```

**Comment by ebkalderon** [comment]
Looks like with commit 3b416e0, this issue is now resolved.
