### ISSUE TITLE
Implement remaining subcommands

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/tools#2]
The following subcommands panic emit an `unimplemented!` when executed without the `(-h | --help)` flag:
- [x] _deploy_ - Compresses and deploys the project as a distributable program
- [ ] _module_ - Adds or removes engine subsystems

This issue will track the development status of these commands.

**Comment by ebkalderon** [comment]
@ogoding If you have any suggestions or questions regarding the `deploy` subcommand, feel free to post them here. It can get quite busy in the Gitter chat sometimes. :smile:

**Comment by ogoding** [comment]
@ebkalderon I think this issue should probably be split up into separate issues as I don't think there is any overlap between them. Nothing else comes to mind, other than that I'm still working on the deploy command.

**Comment by CleanCut** [comment]
👋 I'm closing all PRs and Issues since `amethyst_tools` is being end-of-life'd.  Please see [this forum post](https://community.amethyst.rs/t/end-of-life-for-amethyst-tools-the-cli/1656) for a place to respond and/or discuss the situation rather than here on the repo.
