### ISSUE TITLE
Implement deploy subcommand

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/tools#22]
See the [relevant wiki page](https://github.com/ebkalderon/amethyst/wiki/Project-Structure-Design#published-game-hierarchy) for a description of how the deployed game should look like. This issue is a dependency of #2.

**Comment by White-Oak** [comment]
Bad idea to keep saves in a game folder

**Comment by ebkalderon** [comment]
@White-Oak Could you please elaborate? Keep in mind that the deployed folder contains everything that should be put into the installer. Assuming that the published game is placed in `C:\Program Files\<name>`, where would you prefer these save files be placed instead? Perhaps in something like `AppData/Roaming/mygame` on Windows or `~/.mygame/` on Linux?

**Comment by LucioFranco** [comment]
I know on mac a lot of games like EU4 put game saves in the documents folder. Like ~/Documents/Paradox/EU4/Saves etc.

**Comment by White-Oak** [comment]
The common practice today is to put saves somewhere in home, On windows it is commonly `~/Documents/game_name` or `~/AppData/Roaming/game_name`. Moreover, on Windows 10 you are prohibited to write into Program files if you're not running from administrator, which is a bad practice.

**Comment by ebkalderon** [comment]
That makes sense. Applications should be "good citizens" regardless of the platform they are running on, so it follows that we follow their standards. How does the following scheme seem to you?
- **Windows/OS X**: `~/Documents/game_name/`
- **Linux/BSD**: `~/.game_name/`

In addition to these defaults, this location could also be configurable from `config.yml`, if people want. I can update the wiki page to reflect these changes accordingly.

**Comment by White-Oak** [comment]
@ebkalderon how about `~/.local/share` or `$XDG_DATA_HOME` if it is set on Linux? Afaik, Linux games use that for saves.

**Comment by ebkalderon** [comment]
@White-Oak Sure. Let me look up the standard on XDG real quick so we can be sure we're using it right...

**Edit**: It looks like there is `$XDG_DATA_HOME` for user-specific data files and `$XDG_CONFIG_HOME` for user-specific config files ([source](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)). Should we select one of the two, or use both?

**Comment by White-Oak** [comment]
@ebkalderon I suppose `DATA_HOME` suits us more

**Comment by ogoding** [comment]
@ebkalderon I just saw this discussion, I'll remove the auto create of the saves directory.

**Comment by White-Oak** [comment]
Should probably be closed as #23 was merged.

**Comment by ogoding** [comment]
@ebkalderon An issue for the saved data discussion should be raised I think. I'm not sure if it should be in the engine or this repo, otherwise I'd create it myself.

**Comment by ebkalderon** [comment]
@ogoding I think we should create a new issue for that. I'll close this one in the meantime.
