### ISSUE TITLE
Determine if project is amethyst or not

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/tools#26]
This issue is for discussion on the way that we should determine if we are in an amethyst project directory or not. Related to #25.

**Comment by ebkalderon** [comment]
Since we've discussed and merged #25, I think we can mark this issue as resolved.

**Comment by ebkalderon** [comment]
This still needs some more discussion in how we detect the validity of a given `config.yml` file and `resources` directory structure.

**Comment by ogoding** [comment]
@ebkalderon Is there a set of options that are guaranteed to be used in any given game? Things like title might not be used (e.g. CLI game).

**Comment by White-Oak** [comment]
@ogoding you can discuss ut here https://github.com/amethyst/amethyst/issues/29

**Comment by ogoding** [comment]
@White-Oak Whoops, sorry. Will repost my comment there.

**Comment by Xaeroxe** [comment]
Closing until we can demonstrate why this is necessary
