### ISSUE TITLE
Move new_project.zip into seperate repository

### ISSUE THREAD

**Issue by lschmierer** [amethyst/tools#31]
Because of Git is not good at handling binary blobs and it is not easy to examine the content of `new_project.zip` without downloading and unzipping it, I suggest to put the contents of it into a seperate Git repository.

The repository will be located in `amethyst/project_template`.

The template is included in `amethyst/tools` using Git submodules.
It is bundled together with the tools CLI on build.

Pull request https://github.com/amethyst/tools/pull/32

**Comment by ebkalderon** [comment]
> Copied from Gitter at [April 2, 2016 7:42 AM](https://gitter.im/amethyst/tools?at=56ffb017d9b73e635f688ce5) for records:

I think that's a good idea overall to have the new project standard be in a non-binary file, but I disagree on a few points.
1. I don't think that should store an actual `Cargo.toml` inside the template project. I thought that was decided a while ago after some Gitter discussion that we should generate a real Cargo project by calling into actual Cargo and then applying changes on top of that.
2. I don't believe we should have to connect to the Internet to generate a new project. That seems a little overkill IMO. Once `amethyst_tools` is installed, it should work on your machine as-is without having to download further data that could be more efficiently stored locally.

**Comment by lschmierer** [comment]
`amethyst new` should not connect to the internet, therefore I suggest using the template as submodule within the tools repo.

**Comment by ebkalderon** [comment]
What should we call this repository? Perhaps `amethyst/project_template` or similar?

**Comment by lschmierer** [comment]
This seems good.

**Comment by ebkalderon** [comment]
I think this can be closed with #32 being merged.
