### ISSUE TITLE
Making the build tool a Cargo subcommand

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/tools#36]
Would it be preferable to turn the Amethyst build tool into a [custom subcommand of Cargo](https://github.com/rust-lang/cargo/wiki/Third-party-cargo-subcommands) instead of a full wrapper, as it currently is?

**Comment by LucioFranco** [comment]
I like this idea. What would the sub command be called?

**Comment by White-Oak** [comment]
I suppose it's better not to integrate `Amethyst CLI` into `Cargo`. I just find it very confusing, and it will also be longer to type.

**Comment by torkleyy** [comment]
I don't think this will happen, as discussed before.
