### ISSUE TITLE
Initial scaffold doesn't build

### ISSUE THREAD

**Issue by AphonicChaos** [amethyst/tools#37]
# Description
The out-of-box experience with Amethyst tools is suboptimal due to the generated application not working properly. I was following the steps [from the book](https://www.amethyst.rs/book/getting_started/automatic_setup.html) and failed to get the Hello World example to work. I then tried to make a new project without changing the contents of `src/main.rs` which yielded the results produced in this report.

# Steps to reproduce
1. Create a new project:
```
$ amethyst new hello_world
```
2. Move into that project and attempt to run:
```
$ cd hello_world
$ amethyst run
```
# Expected result
I'd expect to see the result of having run the program. I've never used amethyst before, But I suspect the output should look something like this:
```
$ amethyst run
Game started!
Hello from Amethyst!
Game stopped!
```
# Actual Result
```
error[E0432]: unresolved import `amethyst::engine::Application`
 --> src/main.rs:3:24
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                        ^^^^^^^^^^^ no `Application` in `engine`

error[E0432]: unresolved import `amethyst::engine::Duration`
 --> src/main.rs:3:37
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                                     ^^^^^^^^ no `Duration` in `engine`

error[E0432]: unresolved import `amethyst::engine::State`
 --> src/main.rs:3:47
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                                               ^^^^^ no `State` in `engine`. Did you mean to use `state`?

error[E0432]: unresolved import `amethyst::engine::Trans`
 --> src/main.rs:3:54
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                                                      ^^^^^ no `Trans` in `engine`

error: module `engine` is private
 --> src/main.rs:3:24
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                        ^^^^^^^^^^^

error: module `engine` is private
 --> src/main.rs:3:37
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                                     ^^^^^^^^

error: module `engine` is private
 --> src/main.rs:3:47
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                                               ^^^^^

error: module `engine` is private
 --> src/main.rs:3:54
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                                                      ^^^^^

error: cannot continue compilation due to previous error

error: Could not compile `hello_world`.

To learn more, run the command again with --verbose.
Error: Cargo task failed!

```
# System information
```
$ rustc --version
rustc 1.17.0
$ amethyst --version
amethyst_cli 0.4.0
$ cargo --version
cargo 0.18.0 (fe7b0cdc 2017-04-24)
$ uname -a
Linux vapor 4.10.11-1-ARCH #1 SMP PREEMPT Tue Apr 18 08:39:42 CEST 2017 x86_64 GNU/Linux
```

Here is the contents of the `src/main.rs` file that the `new` command generated:
```rust
extern crate amethyst;

use amethyst::engine::{Application, Duration, State, Trans};

struct HelloWorld;

impl State for HelloWorld {
    fn on_start(&mut self) {
        println!("Game started!");
    }

    fn update(&mut self, _delta: Duration) -> Trans {
        println!("Hello from Amethyst!");
        Trans::Quit
    }

    fn on_stop(&mut self) {
        println!("Game stopped!");
    }
}

fn main() {
    let mut game = Application::new(HelloWorld);
    game.run();
}
```
Note that it's different than what the [tutorial](https://www.amethyst.rs/book/getting_started/hello_world.html) asks me to input. I was getting a different (though similar) set of errors, so wanted to do the minimal amount of work for a reproducible case.

**Comment by AphonicChaos** [comment]
I just installed rustup and from that, grabbed version 1.6.0 of rustc. amethyst_tools failed to install. After that, I got the nightly version of rustc using `rustup default nightly` and was able to `cargo install amethyst_tools` again, but got the above errors.

Without knowing more about rust,it would appear that the interface for various libraries has changed, so the amethyst command is generating deprecated code.

**Comment by torkleyy** [comment]
@aspidites The amethyst tools are not useful atm, the recommended way is to use nightly cargo's `--template` like this:

```bash
cargo +nightly new mygame --template https://github.com/amethyst/project_template
```

The reason its not working here is that the contained project template wasn't updated to point at the latest commit.

**Comment by AphonicChaos** [comment]
@torkleyy given that the life of this project seems uncertain (PR open for a year, a few issues open for months), would it be best to update the book to use that cargo command you mention above? I could start chipping away at it, if so. I'd update the content as I made it through the various pages.

**Comment by AphonicChaos** [comment]
Also:
```
projects ➤ cargo +nightly new mygame --template https://github.com/amethyst/project_template                                                                                
error: no such subcommand: `+nightly`
projects ➤ cargo new mygame --template https://github.com/amethyst/project_template                                                                                         
error: Unknown flag: '--template'
```

**Comment by torkleyy** [comment]
For the first command you need `rustup.rs` and for the latter one nightly cargo. Maybe you installed the stable binary only? I would definitely recommend rustup.

**Comment by AphonicChaos** [comment]
I ran both of those commands with combinations of both rustup's rustc and cargo, as well as my distro's. Namely:
```
~ ➤ which rustup                                                                                                                                                            
/usr/bin/rustup
~ ➤ rustc --version                                                                                                                                                         
rustc 1.19.0-nightly (f4209651e 2017-05-05)
~ ➤ cargo --version                                                                                                                                                         
cargo 0.19.0-nightly (fa7584c14 2017-04-26)
~ ➤ cargo +nightly new mygame --template https://github.com/amethyst/project_template                                                                                       
error: Unknown flag: '--template'

Usage:
    cargo new [options] <path>
    cargo new -h | --help
~ ➤  
```

@torkleyy, are you on Linux?

**Comment by torkleyy** [comment]
I am on Linux, yes. But I don't have rustup installed system-wide. Maybe the template flag was removed recently?
I'll check when I'm at home.

**Comment by AphonicChaos** [comment]
Alright. I'll use the examples and API documentation (if it exists) for now. I'm not in a rush either -- plenty of other side projects to mess with, so if you get a bit tied up, that's totally fine.

Did you want to keep this open to track the issue, or close as it seems it's a "won't fix" given template support?

**Comment by torkleyy** [comment]
I'd keep it open; we definitely should provide a better starting experience.

**Comment by torkleyy** [comment]
@aspidites Checked, does not work for me, too. So I guess it was removed.

@ebkalderon How would you like to continue tools for Amethyst in general? Do we want to use the amethyst cli?

**Comment by torkleyy** [comment]
This should be fixed now.
