### ISSUE TITLE
Discussion about tooling and editors

### ISSUE THREAD

**Issue by Aceeri** [amethyst/tools#38]
NOTE: Please see amethyst/amethyst#875 for more up to date information.

Issue/discussion revolving around the tooling of amethyst. For example, scene editors, visual scripting editors, tree views of components, etc.

Hotreloading should be at the core of most tooling. Modifying an entity file in any way should be updated in the game world for fast iteration. Some basic CLI around amethyst could make this easier:
`amethyst watch` could open an "editor window" and watches for modifications to the files related to the game for updates.

Game state in the editor should be handled in two modes, halted and running In the halted mode the world does not have systems running and no components should be modified by the game. Modifications in this mode should come from tools that can modify the files related to the game and have it updated in the game. Alternatively, tooling could also interact with the game world, for example clicking on some `Mesh` in the editor could highlight the entity related in the tooling as well as able to be moved around.

It would also be ideal if most tooling was under one UI toolkit so it would be possible to have layouts of tools from different libraries. Nuklear seems like a decent choice for a simple but extensive library for handling UI. 

Repo: https://github.com/vurtun/nuklear
Bindings: https://github.com/snuk182/nuklear-rust (beta as it says, so we could probably help out here)

**Comment by torkleyy** [comment]
Thanks for the writeup, I agree with it. That is, however, with one exception: I don't think we need a halted mode; the editor window just shows a preview, so a separate game which happens to show the same world. The behavior of this "preview game" can be customized by the user.

**Comment by erlend-sh** [comment]
I think a bare bones "Project Setup App" is a great way to get newcomers started. This is one thing the very popular LibGDX got right early on:

https://github.com/libgdx/libgdx/wiki/Project-Setup-Gradle

**Comment by LucioFranco** [comment]
@erlend-sh I think the combination of using the book plus the amethyst-cli tool might accomplish that. Still some work to do on the book though.

**Comment by erlend-sh** [comment]
True, a robust CLI might suffice.

@Aceeri I'm curious about this:

> It would also be ideal if most tooling was under one UI toolkit so it would be possible to have layouts of tools from different libraries. Nuklear seems like a decent choice for a simple but extensive library for handling UI.

How does this fit in with [Citrine](https://github.com/Aceeri/citrine)? Are they different use cases or did you change your mind about using Nuklear and opted for pure Rust instead?

Just for the record, similar to Nuklear there is also imgui:

- https://github.com/ocornut/imgui
- https://github.com/Extrawurst/cimgui
- https://github.com/Gekkio/imgui-rs by @gekkio

It's used by @not-fl3 in the SHAR game.

**Comment by Aceeri** [comment]
@erlend-sh Citrine is my experiments to see if I could make a more idiomatic rust UI system, I'd prefer if it were pure rust (since it makes everything a whole lot easier to get set up from a user's perspective), but others can work as well. My end goal I really want to do is having multiple processes (subprocesses?) for different tools to be able to interact with each other like how most other game editors can then just build up our UI around that while allowing users to make the exact same tools from scratch and be able to attach those tools to their own editors. As well as being able to use some of this UI for more in game purposes.

imgui and nuklear are alright choices, they both require C libraries IIRC which makes set up with amethyst a little more annoying (no longer becomes a simple `cargo build`).

**Comment by Hittherhod** [comment]
Would it make sense for the `amethyst watch` command, at least initially, to watch all config files and publish changes, either via stdin or a network (in keeping with the goal of the Unix philosophy)? This might require changes in the amethyst engine to accept external input and convert it to events.

Otherwise, I could see another path, possibly modeling config files as essentially data streams; the file as seen at startup would be the initial state and changes made while running would be like additional messages. Basically they would be modeled like ReactiveX.

**Comment by Moxinilian** [comment]
amethyst/amethyst#875 addresses this

**Comment by erlend-sh** [comment]
This seems relevant to what’s being discussed in 
https://github.com/amethyst/rfcs/pull/6

I still think the LibGDX model is the best way offer a framework/engine hybrid.

**Comment by CleanCut** [comment]
👋 I'm closing all PRs and Issues since `amethyst_tools` is being end-of-life'd.  Please see [this forum post](https://community.amethyst.rs/t/end-of-life-for-amethyst-tools-the-cli/1656) for a place to respond and/or discuss the situation rather than here on the repo.
