### ISSUE TITLE
fail to create new game after deleting tool source

### ISSUE THREAD

**Issue by bytesnail** [amethyst/tools#71]
When I executed the ‘amethyst new’ command, the tool successfully created a new folder, but the creation of the new game project failed, the details are as follows：

lws@lws-deepin:/tool/project/games$ RUST_BACKTRACE=1 amethyst new pong -a 0.10.0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: std::sync::once::Once::call_once::{{closure}}
  10: std::sync::once::Once::call_inner
             at libstd/sync/once.rs:397
  11: amethyst_cli::templates::deploy
  12: amethyst_cli::new::New::execute
  13: amethyst::main
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  16: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  17: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  18: main
  19: __libc_start_main
  20: _start

**Comment by bytesnail** [comment]
I hope anyone can help me solve this problem.

**Comment by LucioFranco** [comment]
try

```bash
mkdir pong
amethyst new pong -a 0.10.0
```

**Comment by bytesnail** [comment]
@LucioFranco 

This way should not work, the code shows that doing this will throw an error:

```rust
let path = Path::new(&self.project_name);
if path.exists() {
    bail!("project directory {:?} already exists", path);
}
```

And I did get this error after trying it:
```shell
lws@lws-deepin:/tool/project/games$ amethyst new pong -a 0.10.0
error: project creation for project "pong" failed
caused by: project directory "pong" already exists
```

**Comment by bytesnail** [comment]
@LucioFranco 

I checked the code, I think the problem is in this code snippet:
```rust
let template_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("templates");
```
The environment variable CARGO_MANIFEST_DIR should be set, I did not see the prompt in the relevant help documentation, and after I installed this tool, this environment variable is not automatically set.

**Comment by bytesnail** [comment]
@LucioFranco 

If you execute 'echo $CARGO_MANIFEST_DIR', what is the result.

I can not find the folder 'templates' in my computer.

**Comment by Rhuagh** [comment]
CARGO_MANIFEST_DIR is a special environment variable that cargo sets when it starts executing a command. I'm not sure if that is possible to use in a compiled build of the tools? Looks like a bug to me.

**Comment by bytesnail** [comment]
Yeah, it works when I run it as 'cargo run --package amethyst_tools --bin amethyst new pong'.

But according to the prompt in the README, the correct way to run should be as follows:

```
amethyst new <project_name>
```

**Comment by bytesnail** [comment]
@Rhuagh 

Is this tool designed as a subcommand of cargo? Otherwise we should not try to use the CARGO_MANIFEST_DIR environment variable in the code.

**Comment by bytesnail** [comment]
@Rhuagh 

I can't find the templates folder on my local computer, so I can't get it to work by manually setting the CARGO_MANIFEST_DIR environment variable. What path is your local templates folder in?

**Comment by sinkuu** [comment]
I encountered the same error message, and fixed it by running `cargo install -f amethyst_tools` again. `amethyst` binary contained an old path where its source directory no longer exists as I have cleaned up `~/.cargo/registry/src`.

**Comment by Xaeroxe** [comment]
This is a old issue that we've resolved in a newer version, so I'm going to close this.

**Comment by torkleyy** [comment]
Are you sure @Xaeroxe? It seems like we're still loading the templates at run-time, assuming they are in the source directory. Isn't that something we ought to fix?

**Comment by Xaeroxe** [comment]
I've tested this recently by installing it from crates and it is working. Though I do see a reference to `CARGO_MANIFEST_DIR` in the source. Also, @sinkuu reported they fixed the problem by installing the latest version.

**Comment by Xaeroxe** [comment]
Ok, so it seems we're dependent on our source directory in the final compiled version. That's the bug. I'll update the issue title to reflect that.

**Comment by BradLugo** [comment]
Can someone provide steps to reproduce this issue and elaborate more on these:
> It seems like we're still loading the templates at run-time, assuming they are in the source directory. Isn't that something we ought to fix?

> Ok, so it seems we're dependent on our source directory in the final compiled version. That's the bug. I'll update the issue title to reflect that.

**Comment by torkleyy** [comment]
Yes.

## Reproduction

1. Clone this repo
2. Build the `amethyst` binary
3. Try running a command (should work)
4. Move the cloned repo, and try again (this should fail)

The reason for that is that we encode the location of the source directory into the binary, which is incorrect.
Instead, the templates should have been included into the binary, which was the case previously (but was changed at some point I believe).

**Comment by BradLugo** [comment]
I've been looking into this the past couple of days. The best solution I've come up with is using a [build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html) to generate a file that creates a tuple for the file name and [include_str](https://doc.rust-lang.org/std/macro.include_str.html) call to the file name. Then use [include](https://doc.rust-lang.org/std/macro.include.html) to parse said tuple from said generated file. This solution also allows for version detection during compilation, so the liquid renderings are the only file operations during runtime.

I want to get other opinions on how to resolve this, as the implementation I suggested seems quite heavy-handed. 

> Instead, the templates should have been included into the binary, which was the case previously

This also leads me to believe my suggestion is overly complicated.

**Comment by torkleyy** [comment]
No, that sounds good. It's pretty similar to what I did in my original rewrite.
