### ISSUE TITLE
amethyst cli doesn't init git repo

### ISSUE THREAD

**Issue by Willowblade** [amethyst/tools#73]
See #10, there is also no .gitignore created (but these go hand in hand)

As the amethyst CLI tries to emulate cargo cli, in my opinion it should also initialize a git repo like cargo does.

### Amethyst CLI (sorry for the time it took me to derp around)

![peek 2019-01-15 17-19](https://user-images.githubusercontent.com/3596182/51193876-2ee9d100-18ea-11e9-9a30-109d81066f04.gif)

### Cargo CLI

![peek 2019-01-15 17-22](https://user-images.githubusercontent.com/3596182/51193880-301afe00-18ea-11e9-9491-5b53e291c159.gif)

**Comment by Xaeroxe** [comment]
That's fair, thanks!

**Comment by LucioFranco** [comment]
Yup, this would be great! Should be as easy as just calling this https://docs.rs/git2/0.8.0/git2/struct.Repository.html#method.init
