### ISSUE TITLE
Implement `amethyst deploy`

### ISSUE THREAD

**Issue by torkleyy** [amethyst/tools#76]
I think it would be great to have some way to deploy an Amethyst game, and the CLI seems like a good place to implement this.

## Initial implementation

An initial implementation could be to simply do a release build on the host platform, copy `resources` + `assets` if they exist and package it into a zip / tar.

## Further improvements

* Do cross-compilation for other platforms
* Create installers
* Allow to configure other directories to copy

**Comment by BradLugo** [comment]
Did you want this done via a wrapper around `std::process::Command` and `cargo` or using the [cargo library](https://docs.rs/cargo/0.36.0/cargo/index.html)?

**Comment by torkleyy** [comment]
I think both work. The `cargo` library gives us more freedom, but it also increases compile times a lot. So I'd probably go for the `Command` here.

**Comment by CleanCut** [comment]
👋 I'm closing all PRs and Issues since `amethyst_tools` is being end-of-life'd.  Please see [this forum post](https://community.amethyst.rs/t/end-of-life-for-amethyst-tools-the-cli/1656) for a place to respond and/or discuss the situation rather than here on the repo.
