### ISSUE TITLE
Implement `amethyst generate`

### ISSUE THREAD

**Issue by BradLugo** [amethyst/tools#78]
As a developer of an Amethyst based project, I'd like the Amethyst cli to be able to generate basic building blocks without having to copy and paste boilerplate myself.

#58 includes most of these changes but needs to be rebased, and some of the logic needs to be changed as per the discussion in that PR.

Generator Subtasks:
- [ ] State
- [ ] Component
- [ ] System

Other ideas for the generator command and other constituents the generator should be able to create are welcome!

**Comment by CleanCut** [comment]
👋 I'm closing all PRs and Issues since `amethyst_tools` is being end-of-life'd.  Please see [this forum post](https://community.amethyst.rs/t/end-of-life-for-amethyst-tools-the-cli/1656) for a place to respond and/or discuss the situation rather than here on the repo.
