### ISSUE TITLE
Implement `amethyst destroy`

### ISSUE THREAD

**Issue by BradLugo** [amethyst/tools#79]
Contrasting to #78, I'd like to use the Amethyst cli to delete the building blocks it's able to create. I'd think the `generate` command and `destroy` command should be consistent in the constituents they create/delete. If you have any suggestions for said constituents, please do so in #78.

Destroyer Subtasks:
- [ ] State
- [ ] Component
- [ ] System

**Comment by CleanCut** [comment]
👋 I'm closing all PRs and Issues since `amethyst_tools` is being end-of-life'd.  Please see [this forum post](https://community.amethyst.rs/t/end-of-life-for-amethyst-tools-the-cli/1656) for a place to respond and/or discuss the situation rather than here on the repo.
