### ISSUE TITLE
Rename repo to amethyst-cli

### ISSUE THREAD

**Issue by BradLugo** [amethyst/tools#80]
The rewrite from #39 changes the intention behind the current repo's name. Discussed in #75, the repository name should be changed to `amethyst-cli`. The topic for the repository should also be modified.

**Comment by CleanCut** [comment]
👋 I'm closing all PRs and Issues since `amethyst_tools` is being end-of-life'd.  Please see [this forum post](https://community.amethyst.rs/t/end-of-life-for-amethyst-tools-the-cli/1656) for a place to respond and/or discuss the situation rather than here on the repo.
