### ISSUE TITLE
Add functionality for addition template types

### ISSUE THREAD

**Issue by BradLugo** [amethyst/tools#83]
#81 changed the way templates types are handled back to only being `main`. The lack of this functionality will block development on #78 and #79.

**Comment by BradLugo** [comment]
I'm trying to decide a good way to do this. The best solution I've come up with so far is to delete all of the `index.ron` files in `templates/<version-number>/<template-name>` and create `index.ron` or `templates.ron` either to `templates` or the root of the project with an object structure something like this:
```
Templates(
    <version-number>: {
        <template-name>: [
            "<file-name>",
            "<file-name>",
        ],
        <template-name>: [
            "<file-name>",
            "<file-name>",
        ]
    },
    <version-number>: {
        <template-name>: [
            "<file-name>",
            "<file-name>",
        ],
        <template-name>: [
            "<file-name>",
            "<file-name>",
        ]
    }
)
```

Thoughts?

**Comment by torkleyy** [comment]
Why do you need to put it all into on RON file? I'd just leave it in the individual files, but change the contents to a struct.

**Comment by BradLugo** [comment]
That's definitely on the table. My thought was that having the versions and template types in a single RON file would allow us to compile and know exactly what files are included. I'm not a _huge_ fan of relying on the filesystem for data consistency, i.e., the compilation would fail if we configured a version in the RON file and the compiler couldn't find it vs. the compiler not seeing it the version in the filesystem and not including it but compiling successfully anyway.

At a certain point, I'm over-engineering this, so I'm ok with implementing it the way you suggested.

**Comment by torkleyy** [comment]
I see. Well, I think both solutions are okay. I'm pretty sure it's fine to trust the file system though ^^

**Comment by BradLugo** [comment]
Ultimately, y'all are the maintainers, so I'll implement what y'all think is best. Left to my own devices though, I'm going to choose the single file solution unless you tell me otherwise.

**Comment by torkleyy** [comment]
Sounds good :+1:

**Comment by CleanCut** [comment]
👋 I'm closing all PRs and Issues since `amethyst_tools` is being end-of-life'd.  Please see [this forum post](https://community.amethyst.rs/t/end-of-life-for-amethyst-tools-the-cli/1656) for a place to respond and/or discuss the situation rather than here on the repo.
