### ISSUE TITLE
`amethyst new` doesn't put authors in Cargo.toml

### ISSUE THREAD

**Issue by White-Oak** [amethyst/tools#9]
It is probably not so easy, but I think it is possible to get git name and email on a system and add put them into `author` field of Cargo.toml.

**Comment by ebkalderon** [comment]
> Note: This proposal will also solve issues #8 and #10.

We may be able to work around manual manipulation of the TOML text. I propose the following:
1. Only the `src` and `resources` directories remain in the "new_project.zip" file.
2. At runtime, `amethyst new [name]` calls `cargo new [name]`. A fresh Cargo project is created.
3. The contents of "new_project.zip" are unzipped into the newly-created folder.
4. The `[dependencies]` details are appended to the end of the "Cargo.toml" file.

Does that seem reasonable to you?

**Comment by White-Oak** [comment]
Yes, it is a much better and easier approach!

**Comment by ebkalderon** [comment]
Cool! I can get started working on it a bit later today, though if you're impatient and would like to submit a pull request sooner, I welcome it. :wink:

**Comment by White-Oak** [comment]
@ebkalderon yeah, I would like to submit a pull request if you don't mind :)

**Comment by ebkalderon** [comment]
@White-Oak Please, go right ahead. :smile:

**Comment by ebkalderon** [comment]
This has been fixed by pull request #12. Marking as resolved and closing.
