### ISSUE TITLE
amethyst new <name> do not compile in 0.13.2

### ISSUE THREAD

**Issue by jmwielandt** [amethyst/tools#97]
Hi,

As the title says, the base project do not compile.

<hr/>

**EDIT:** in 0.12.0 it compiles propperly. I think #91 is not solved.

<hr/>

Here's the error:

![image](https://user-images.githubusercontent.com/37153467/69919291-234bbe00-145a-11ea-8a60-ba89bd16c14f.png)

Greetings!

**Comment by 0x6273** [comment]
It seems to compile on both 0.12.0 and 0.13.2 if you remove the `ecs::prelude::{..}` line.
